import { RegionName, Upgrade, Question, AcademicEra, Stock, MinigameDefinition, Hardware, NetworkDevice, MatterOperationDefinition } from './types';

export const INITIAL_STOCKS: Stock[] = [
  {
    id: 'python_grind',
    ticker: 'PYN',
    name: 'Learn Python at 2AM',
    description: 'Late-night code binges can boost productivity and dopamine... until the existential traceback.',
    riskDescription: 'Can rally hard, but burnout cascades can nuke confidence and price to almost zero.',
    detailOnClick: 'Momentum follows consistency. Miss too many sessions and the market prices in a crash-out.',
    currentPrice: 95,
    minPrice: 0,
    maxPrice: 620,
    owned: 0,
    history: Array(20).fill(95),
    volatility: 0.16,
    trend: 0.012,
    crashChance: 0.035,
    moonChance: 0.06,
    recoveryChance: 0.22,
    liquidity: 0.72,
    transactionFee: 0.012,
    riskLevel: 'High'
  },
  {
    id: 'meal_prep_discipline',
    ticker: 'PREP',
    name: 'Meal Prep Sundays',
    description: 'Stability stock. Boring gains from not panic-ordering fries during assignment week.',
    riskDescription: 'Lower upside, but fewer catastrophic drawdowns.',
    detailOnClick: 'Defensive asset. Usually mean-reverts and absorbs market panic well.',
    currentPrice: 78,
    minPrice: 28,
    maxPrice: 260,
    owned: 0,
    history: Array(20).fill(78),
    volatility: 0.06,
    trend: 0.01,
    crashChance: 0.004,
    moonChance: 0.016,
    recoveryChance: 0.08,
    liquidity: 0.9,
    transactionFee: 0.007,
    riskLevel: 'Medium'
  },
  {
    id: 'gym_arc',
    ticker: 'GA1N',
    name: 'Gym Arc + Creatine Lore',
    description: 'Confidence compounds when the routine hits. Deload weeks can trigger dramatic selloffs.',
    riskDescription: 'Trend-following asset with boom-bust cycles around motivation.',
    detailOnClick: 'Strong in bull moods. Prone to sharp corrections after overextended runs.',
    currentPrice: 160,
    minPrice: 18,
    maxPrice: 1900,
    owned: 0,
    history: Array(20).fill(160),
    volatility: 0.14,
    trend: 0.018,
    crashChance: 0.018,
    moonChance: 0.055,
    recoveryChance: 0.12,
    liquidity: 0.68,
    transactionFee: 0.011,
    riskLevel: 'High'
  },
  {
    id: 'doomscroll_quant',
    ticker: 'SCRL',
    name: 'Doomscroll Quant Fund',
    description: 'Weaponized overthinking monetized into chaotic micro-trends.',
    riskDescription: 'Extreme leverage to mood swings. Can moon overnight or evaporate by breakfast.',
    detailOnClick: 'Pure chaos asset. High slippage, high spreads, high regret.',
    currentPrice: 420,
    minPrice: 0,
    maxPrice: 6200,
    owned: 0,
    history: Array(20).fill(420),
    volatility: 0.28,
    trend: -0.004,
    crashChance: 0.05,
    moonChance: 0.09,
    recoveryChance: 0.26,
    liquidity: 0.42,
    transactionFee: 0.018,
    riskLevel: 'Extreme'
  },
  {
    id: 'side_hustle_alchemy',
    ticker: 'HUST',
    name: 'Side Hustle Alchemy',
    description: 'Turns random hobbies into suspiciously optimized cashflow dashboards.',
    riskDescription: 'Sensitive to platform algorithm shifts and self-worth tied to analytics.',
    detailOnClick: 'Works until the algorithm changes. Then everyone pretends they were always in bonds.',
    currentPrice: 210,
    minPrice: 5,
    maxPrice: 3600,
    owned: 0,
    history: Array(20).fill(210),
    volatility: 0.19,
    trend: 0.014,
    crashChance: 0.02,
    moonChance: 0.06,
    recoveryChance: 0.1,
    liquidity: 0.56,
    transactionFee: 0.014,
    riskLevel: 'Extreme'
  }
];

export const BONUS_STOCKS: Stock[] = [
  {
    id: 'lucid_daytrade',
    ticker: 'LUCID',
    name: 'Lucid Daytrade Journal',
    description: 'You started tracking your thoughts and accidentally discovered market timing. Extremely temporary superpower.',
    riskDescription: 'Great upside, but one bad sleep cycle and the edge disappears.',
    detailOnClick: 'Unlocked via visual pattern mastery. Volatile, trend-friendly, emotionally hazardous.',
    currentPrice: 680,
    minPrice: 0,
    maxPrice: 9000,
    owned: 0,
    history: Array(20).fill(680),
    volatility: 0.25,
    trend: 0.03,
    crashChance: 0.045,
    moonChance: 0.09,
    recoveryChance: 0.2,
    liquidity: 0.44,
    transactionFee: 0.019,
    totalCostBasis: 0,
    realizedPnl: 0,
    riskLevel: 'Extreme'
  },
  {
    id: 'thesis_leverage',
    ticker: 'THES',
    name: 'Thesis Leverage ETF',
    description: 'Concentrated position in one very confident interpretation of one paper.',
    riskDescription: 'May print absurd gains or collapse when someone reads the methods section.',
    detailOnClick: 'Unlocked by executive overconfidence. High beta to intellectual hubris.',
    currentPrice: 920,
    minPrice: 5,
    maxPrice: 12000,
    owned: 0,
    history: Array(20).fill(920),
    volatility: 0.29,
    trend: 0.018,
    crashChance: 0.05,
    moonChance: 0.1,
    recoveryChance: 0.18,
    liquidity: 0.38,
    transactionFee: 0.022,
    totalCostBasis: 0,
    realizedPnl: 0,
    riskLevel: 'Extreme'
  }
];

export const UPGRADES_DATA: Upgrade[] = [
  {
    id: 'note_chunking',
    region: RegionName.Brainstem,
    name: 'Note Chunking',
    description: 'Break information into manageable units. +1 click power.',
    cost: 15,
    currency: 'neurons',
    effectType: 'click',
    value: 1,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 12,
    count: 0
  },
  {
    id: 'study_routine',
    region: RegionName.Brainstem,
    name: 'Study Routine',
    description: 'Daily review cycle. +2 passive neurons/sec.',
    cost: 45,
    currency: 'neurons',
    effectType: 'passive',
    value: 2,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 20,
    count: 0
  },
  {
    id: 'focus_microbursts',
    region: RegionName.Brainstem,
    name: 'Focus Microbursts',
    description: 'Short tactical sprints. +1.5% critical focus chance.',
    cost: 120,
    currency: 'neurons',
    effectType: 'crit_chance',
    value: 0.015,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 8,
    count: 0
  },
  {
    id: 'caffeine_spiral',
    region: RegionName.Brainstem,
    name: 'Caffeine Spiral',
    description: 'Questionable beverage engineering. Better streak scaling.',
    cost: 25,
    currency: 'dopamine',
    effectType: 'streak_boost',
    value: 0.01,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 6,
    count: 0
  },
  {
    id: 'motor_rehearsal',
    region: RegionName.Cerebellum,
    name: 'Motor Rehearsal',
    description: 'Repetition improves procedural fluency. +2 click power.',
    cost: 100,
    currency: 'neurons',
    effectType: 'click',
    value: 2,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 8,
    count: 0
  },
  {
    id: 'retrieval_drills',
    region: RegionName.Cerebellum,
    name: 'Retrieval Drills',
    description: 'Practice without notes. +6 passive neurons/sec.',
    cost: 160,
    currency: 'neurons',
    effectType: 'passive',
    value: 6,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 12,
    count: 0
  },
  {
    id: 'motor_overclock',
    region: RegionName.Cerebellum,
    name: 'Motor Overclock',
    description: 'Your mouse hand now has graduate-level precision. +4 click power.',
    cost: 320,
    currency: 'neurons',
    effectType: 'click',
    value: 4,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 8,
    count: 0
  },
  {
    id: 'muscle_memory_chain',
    region: RegionName.Cerebellum,
    name: 'Muscle Memory Chain',
    description: 'Rapid clicking compounds harder before fatigue sets in.',
    cost: 35,
    currency: 'serotonin',
    effectType: 'streak_boost',
    value: 0.015,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 6,
    count: 0
  },
  {
    id: 'reward_schedule',
    region: RegionName.Limbic,
    name: 'Reward Schedule',
    description: 'Planned rewards improve persistence. +0.12 dopamine gain.',
    cost: 10,
    currency: 'dopamine',
    effectType: 'dopamine_gain',
    value: 0.1,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 8,
    count: 0
  },
  {
    id: 'emotion_regulation',
    region: RegionName.Limbic,
    name: 'Emotion Regulation',
    description: 'Breathing and reappraisal. Anxiety rises slower.',
    cost: 20,
    currency: 'serotonin',
    effectType: 'anxiety_resist',
    value: 0.9,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 8,
    count: 0
  },
  {
    id: 'parasympathetic_reset',
    region: RegionName.Limbic,
    name: 'Parasympathetic Reset',
    description: 'Downshift the threat response. Raises stress threshold before breakdown.',
    cost: 28,
    currency: 'serotonin',
    effectType: 'anxiety_cap',
    value: 12,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 6,
    count: 0
  },
  {
    id: 'dopamine_tunnel',
    region: RegionName.Limbic,
    name: 'Dopamine Tunnel Vision',
    description: 'Critical hits now hit harder. +0.25 crit multiplier.',
    cost: 45,
    currency: 'dopamine',
    effectType: 'crit_mult',
    value: 0.25,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 6,
    count: 0
  },
  {
    id: 'mood_lighting',
    region: RegionName.Limbic,
    name: 'Mood Lighting',
    description: 'Installs dramatic UI effects. Click bursts now look expensive.',
    cost: 30,
    currency: 'serotonin',
    effectType: 'visual_fx',
    value: 1,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 3,
    count: 0
  },
  {
    id: 'memory_palace',
    region: RegionName.Temporal,
    name: 'Memory Palace',
    description: 'Spatial cues for long-term recall. +16 passive neurons/sec.',
    cost: 750,
    currency: 'neurons',
    effectType: 'passive',
    value: 14,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 10,
    count: 0
  },
  {
    id: 'spaced_repetition',
    region: RegionName.Temporal,
    name: 'Spaced Repetition',
    description: 'Schedule reviews by forgetting curve. +10 serotonin gain.',
    cost: 45,
    currency: 'dopamine',
    effectType: 'serotonin_gain',
    value: 8,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 6,
    count: 0
  },
  {
    id: 'mnemonic_recursion',
    region: RegionName.Temporal,
    name: 'Mnemonic Recursion',
    description: 'You remember remembering things. +0.3 crit multiplier.',
    cost: 420,
    currency: 'neurons',
    effectType: 'crit_mult',
    value: 0.3,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 5,
    count: 0
  },
  {
    id: 'context_indexing',
    region: RegionName.Temporal,
    name: 'Context Indexing',
    description: 'Everything gets tagged and retrievable. +35 passive neurons/sec.',
    cost: 70,
    currency: 'dopamine',
    effectType: 'passive',
    value: 35,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 6,
    count: 0
  },
  {
    id: 'data_visuals',
    region: RegionName.Parietal,
    name: 'Data Visualisation',
    description: 'Graphs accelerate interpretation. +20 click power.',
    cost: 1200,
    currency: 'neurons',
    effectType: 'click',
    value: 20,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 6,
    count: 0
  },
  {
    id: 'statistics_tutor',
    region: RegionName.Parietal,
    name: 'Statistics Tutor',
    description: 'Targeted support in inferential reasoning. +15 anxiety cap.',
    cost: 65,
    currency: 'serotonin',
    effectType: 'anxiety_cap',
    value: 15,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 5,
    count: 0
  },
  {
    id: 'fractal_notebooks',
    region: RegionName.Parietal,
    name: 'Fractal Notebooks',
    description: 'Every diagram implies three more diagrams. +55 click power.',
    cost: 2100,
    currency: 'neurons',
    effectType: 'click',
    value: 55,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 5,
    count: 0
  },
  {
    id: 'bayes_burst',
    region: RegionName.Parietal,
    name: 'Bayes Burst',
    description: 'Posterior confidence surges. +2% crit chance.',
    cost: 65,
    currency: 'serotonin',
    effectType: 'crit_chance',
    value: 0.02,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 5,
    count: 0
  },
  {
    id: 'case_patterning',
    region: RegionName.Occipital,
    name: 'Case Patterning',
    description: 'Recognise patterns across studies. +55 passive neurons/sec.',
    cost: 3600,
    currency: 'neurons',
    effectType: 'passive',
    value: 48,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 8,
    count: 0
  },
  {
    id: 'attentional_filter',
    region: RegionName.Occipital,
    name: 'Attentional Filter',
    description: 'Reduce distractor interference. Anxiety rises slower.',
    cost: 80,
    currency: 'serotonin',
    effectType: 'anxiety_resist',
    value: 0.82,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 4,
    count: 0
  },
  {
    id: 'aesthetic_overdrive',
    region: RegionName.Occipital,
    name: 'Aesthetic Overdrive',
    description: 'The click button now emits extremely academic glow.',
    cost: 90,
    currency: 'serotonin',
    effectType: 'visual_fx',
    value: 1,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 3,
    count: 0
  },
  {
    id: 'pattern_arbitrage',
    region: RegionName.Occipital,
    name: 'Pattern Arbitrage',
    description: 'Unlocks a new market: Lucid Daytrade Journal.',
    cost: 160,
    currency: 'dopamine',
    effectType: 'stock_unlock',
    value: 0,
    unlockStockId: 'lucid_daytrade',
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 1,
    count: 0
  },
  {
    id: 'executive_control',
    region: RegionName.Frontal,
    name: 'Executive Control',
    description: 'Strategic planning and inhibition. +280 passive neurons/sec.',
    cost: 100,
    currency: 'dopamine',
    effectType: 'passive',
    value: 220,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 6,
    count: 0
  },
  {
    id: 'exam_simulator',
    region: RegionName.Frontal,
    name: 'Exam Simulator',
    description: 'Practice timed responses. +140 click power.',
    cost: 105,
    currency: 'serotonin',
    effectType: 'click',
    value: 110,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 4,
    count: 0
  },
  {
    id: 'executive_gambit',
    region: RegionName.Frontal,
    name: 'Executive Gambit',
    description: 'Calculated risk taking. +0.5 crit multiplier.',
    cost: 140,
    currency: 'dopamine',
    effectType: 'crit_mult',
    value: 0.5,
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 5,
    count: 0
  },
  {
    id: 'quant_brainstorm',
    region: RegionName.Frontal,
    name: 'Quant Brainstorm',
    description: 'Unlocks Thesis Leverage ETF. Nobody can stop you now.',
    cost: 180,
    currency: 'serotonin',
    effectType: 'stock_unlock',
    value: 0,
    unlockStockId: 'thesis_leverage',
    purchased: false,
    reqRegionLevel: 1,
    maxPurchases: 1,
    count: 0
  }
];

export const QUESTIONS: Question[] = [
  {
    id: 'q_smooth_1',
    text: 'In classical conditioning, the stimulus that naturally triggers a response is called the:',
    options: ['Conditioned stimulus', 'Unconditioned stimulus', 'Neutral stimulus', 'Discriminative stimulus'],
    correctIndex: 1,
    era: AcademicEra.SmoothBrain,
    explanation: 'The unconditioned stimulus (UCS) naturally produces an unconditioned response without prior learning.'
  },
  {
    id: 'q_smooth_2',
    text: 'Which memory store has the largest capacity and potentially unlimited duration?',
    options: ['Sensory memory', 'Short-term memory', 'Working memory', 'Long-term memory'],
    correctIndex: 3,
    era: AcademicEra.SmoothBrain,
    explanation: 'Long-term memory is generally considered to have very large capacity and durable retention.'
  },
  {
    id: 'q_smooth_3',
    text: 'A variable that is measured to see if it changes is the:',
    options: ['Independent variable', 'Dependent variable', 'Controlled variable', 'Extraneous variable'],
    correctIndex: 1,
    era: AcademicEra.SmoothBrain,
    explanation: 'The dependent variable is the outcome you measure in an experiment.'
  },
  {
    id: 'q_smooth_4',
    text: 'Negative reinforcement increases behavior by:',
    options: ['Adding something unpleasant', 'Removing something unpleasant', 'Adding reward points only', 'Ignoring the behavior'],
    correctIndex: 1,
    era: AcademicEra.SmoothBrain,
    explanation: 'Negative reinforcement strengthens behavior by removing an aversive stimulus.'
  },
  {
    id: 'q_wiki_1',
    text: 'In a repeated-measures design, participants:',
    options: ['Are split into independent groups', 'Complete all experimental conditions', 'Are observed only once', 'Are selected only by random sampling'],
    correctIndex: 1,
    era: AcademicEra.WikiSkimmer,
    explanation: 'Repeated-measures means the same participants are tested across multiple conditions.'
  },
  {
    id: 'q_wiki_2',
    text: 'The role of the hippocampus is most strongly associated with:',
    options: ['Fine motor control', 'Visual processing', 'Formation of new long-term memories', 'Hormone release'],
    correctIndex: 2,
    era: AcademicEra.WikiSkimmer,
    explanation: 'The hippocampus supports consolidation and formation of many new explicit memories.'
  },
  {
    id: 'q_wiki_3',
    text: 'A distribution where most scores cluster around the mean is called:',
    options: ['Bimodal distribution', 'Skewed distribution', 'Normal distribution', 'Random distribution'],
    correctIndex: 2,
    era: AcademicEra.WikiSkimmer,
    explanation: 'A normal distribution is symmetric, bell-shaped, and centered around the mean.'
  },
  {
    id: 'q_wiki_4',
    text: 'In operant conditioning, behavior is shaped primarily by:',
    options: ['Reflexes only', 'Consequences', 'Genetic drift', 'Sensory thresholds'],
    correctIndex: 1,
    era: AcademicEra.WikiSkimmer,
    explanation: 'Operant conditioning focuses on how reinforcement and punishment affect voluntary behavior.'
  },
  {
    id: 'q_undergrad_1',
    text: 'Which statement best describes a confounding variable?',
    options: ['It is the variable deliberately manipulated', 'It co-varies with the IV and can affect the DV', 'It is a constant in all conditions', 'It is the measured outcome'],
    correctIndex: 1,
    era: AcademicEra.Undergrad,
    explanation: 'A confound is linked to the IV and can provide an alternative explanation for changes in the DV.'
  },
  {
    id: 'q_undergrad_2',
    text: 'Why are placebo controls useful in treatment studies?',
    options: ['They eliminate all participant differences', 'They control expectancy effects', 'They increase ecological validity only', 'They remove need for ethics review'],
    correctIndex: 1,
    era: AcademicEra.Undergrad,
    explanation: 'Placebo controls reduce expectancy and demand characteristics when evaluating treatment effects.'
  },
  {
    id: 'q_undergrad_3',
    text: 'Semantic memory refers to memory for:',
    options: ['Personal life events', 'General facts and concepts', 'Motor skills', 'Sensory traces only'],
    correctIndex: 1,
    era: AcademicEra.Undergrad,
    explanation: 'Semantic memory stores decontextualized knowledge such as meanings, facts, and concepts.'
  },
  {
    id: 'q_undergrad_4',
    text: 'The serial position effect includes better recall for items at the beginning and end of a list due to:',
    options: ['Placebo and nocebo effects', 'Primacy and recency effects', 'Interference and displacement only', 'Schema and script effects'],
    correctIndex: 1,
    era: AcademicEra.Undergrad,
    explanation: 'Primacy and recency effects explain why first and last items are often recalled better.'
  },
  {
    id: 'q_undergrad_5',
    text: 'In ethics, informed consent means participants:',
    options: ['Must know every hypothesis detail before debrief', 'Understand procedures, risks, and rights before agreeing', 'Can never withdraw once started', 'Must be paid to participate'],
    correctIndex: 1,
    era: AcademicEra.Undergrad,
    explanation: 'Informed consent requires clear understanding of participation and the right to withdraw.'
  },
  {
    id: 'q_undergrad_6',
    text: 'Neurotransmitters are best described as:',
    options: ['Electrical impulses in bones', 'Chemical messengers between neurons', 'Hormones produced only in adrenal glands', 'Genes that code for behavior'],
    correctIndex: 1,
    era: AcademicEra.Undergrad,
    explanation: 'Neurotransmitters transmit signals across synapses from one neuron to another.'
  },
  {
    id: 'q_asc_1',
    text: 'Random allocation in experiments primarily improves:',
    options: ['Construct validity', 'Participant motivation', 'Group equivalence', 'Sample size'],
    correctIndex: 2,
    era: AcademicEra.Ascended,
    explanation: 'Random allocation helps distribute participant variables evenly across conditions.'
  },
  {
    id: 'q_asc_2',
    text: 'Counterbalancing in repeated-measures designs addresses:',
    options: ['Sampling bias', 'Order effects', 'Experimenter bias', 'Social desirability'],
    correctIndex: 1,
    era: AcademicEra.Ascended,
    explanation: 'Counterbalancing reduces order effects such as practice and fatigue.'
  },
  {
    id: 'q_asc_3',
    text: 'If two variables have a strong positive correlation, we can conclude that:',
    options: ['One variable definitely causes the other', 'A third variable cannot exist', 'They increase together but causation is not confirmed', 'The relationship is always linear and causal'],
    correctIndex: 2,
    era: AcademicEra.Ascended,
    explanation: 'Correlation indicates association, not direct causation.'
  },
  {
    id: 'q_asc_4',
    text: 'In evaluating research quality, reliability refers to:',
    options: ['Whether findings are statistically significant', 'Consistency of a measure or procedure', 'Whether a design is experimental', 'How quickly data was collected'],
    correctIndex: 1,
    era: AcademicEra.Ascended,
    explanation: 'Reliability concerns consistency and repeatability of measurement.'
  },
  {
    id: 'q_asc_5',
    text: 'A participant changing behavior because they know they are being studied is an example of:',
    options: ['The Hawthorne effect', 'Retroactive interference', 'Long-term potentiation', 'Habituation'],
    correctIndex: 0,
    era: AcademicEra.Ascended,
    explanation: 'The Hawthorne effect describes behavior change due to awareness of observation.'
  },
  {
    id: 'q_asc_6',
    text: 'Which design would best test a causal link between sleep restriction and attention?',
    options: ['Correlational survey', 'Case study only', 'Controlled experiment with manipulation of sleep duration', 'Naturalistic observation'],
    correctIndex: 2,
    era: AcademicEra.Ascended,
    explanation: 'A controlled experiment with manipulated IV and controlled variables is strongest for causal inference.'
  },
  {
    id: 'q_qcaa_1',
    text: 'Which statement best captures the materialist approach to the mind-body problem?',
    options: ['Mind and body are separate substances', 'Mental processes are brain processes', 'Consciousness is unrelated to physiology', 'The soul controls all behavior independently'],
    correctIndex: 1,
    era: AcademicEra.SmoothBrain,
    explanation: 'Materialism argues that mental activity is produced by physical brain activity.'
  },
  {
    id: 'q_qcaa_2',
    text: 'René Descartes is most strongly linked to which view?',
    options: ['Behaviorism', 'Dualism', 'Empiricism only', 'Structuralism'],
    correctIndex: 1,
    era: AcademicEra.SmoothBrain,
    explanation: 'Descartes is known for dualism: mind and body are distinct.'
  },
  {
    id: 'q_qcaa_3',
    text: 'Phrenology (Franz Gall) is now rejected mainly because:',
    options: ['It had no claims about brain function', 'Skull bumps do not validly map psychological traits', 'It required MRI evidence', 'It focused on neurotransmitters'],
    correctIndex: 1,
    era: AcademicEra.WikiSkimmer,
    explanation: 'Phrenology relied on invalid assumptions about skull shape and mental traits.'
  },
  {
    id: 'q_qcaa_4',
    text: 'Flourens and Penfield contributed to neuroscience primarily through:',
    options: ['Twin studies', 'Experimental neurosurgery and cortical stimulation/lesion evidence', 'Brain training apps', 'Questionnaire-only research'],
    correctIndex: 1,
    era: AcademicEra.WikiSkimmer,
    explanation: 'Both helped map function by invasive methods such as lesions and stimulation.'
  },
  {
    id: 'q_qcaa_5',
    text: 'Which neuroimaging method has high temporal resolution and records electrical activity directly?',
    options: ['MRI', 'PET', 'EEG', 'fMRI'],
    correctIndex: 2,
    era: AcademicEra.WikiSkimmer,
    explanation: 'EEG directly measures electrical activity with millisecond timing.'
  },
  {
    id: 'q_qcaa_6',
    text: 'A key strength of fMRI relative to EEG is:',
    options: ['Direct measure of action potentials', 'Higher spatial resolution for localising activity', 'Cheaper setup in classrooms', 'No sensitivity to movement'],
    correctIndex: 1,
    era: AcademicEra.Undergrad,
    explanation: 'fMRI provides stronger spatial localisation than EEG.'
  },
  {
    id: 'q_qcaa_7',
    text: 'The central nervous system consists of:',
    options: ['Brain and spinal cord', 'Somatic and autonomic systems only', 'Nerves and ganglia only', 'Endocrine glands'],
    correctIndex: 0,
    era: AcademicEra.SmoothBrain,
    explanation: 'CNS = brain + spinal cord.'
  },
  {
    id: 'q_qcaa_8',
    text: 'Which part of a neuron primarily receives incoming signals?',
    options: ['Axon terminal', 'Myelin sheath', 'Dendrites', 'Nodes of Ranvier'],
    correctIndex: 2,
    era: AcademicEra.SmoothBrain,
    explanation: 'Dendrites receive most incoming synaptic input.'
  },
  {
    id: 'q_qcaa_9',
    text: 'Motor neurons are best described as neurons that:',
    options: ['Carry sensory information to CNS', 'Connect sensory neurons only', 'Transmit commands from CNS to muscles/glands', 'Form the blood-brain barrier'],
    correctIndex: 2,
    era: AcademicEra.WikiSkimmer,
    explanation: 'Motor neurons transmit outputs from CNS to effectors.'
  },
  {
    id: 'q_qcaa_10',
    text: 'Viewing the brain as hindbrain, midbrain, and forebrain is an example of:',
    options: ['Cellular classification', 'Discrete anatomical organisation', 'Neurochemical hierarchy only', 'Dualist analysis'],
    correctIndex: 1,
    era: AcademicEra.WikiSkimmer,
    explanation: 'These divisions reflect broad discrete anatomical regions.'
  },
  {
    id: 'q_qcaa_11',
    text: 'Damage to Broca’s area most commonly affects:',
    options: ['Speech production fluency', 'Visual acuity', 'Balance and posture', 'Auditory thresholds only'],
    correctIndex: 0,
    era: AcademicEra.Undergrad,
    explanation: 'Broca’s area is strongly associated with speech production.'
  },
  {
    id: 'q_qcaa_12',
    text: 'Wernicke’s area is most associated with:',
    options: ['Motor planning', 'Language comprehension', 'Fear conditioning only', 'Reflex arcs'],
    correctIndex: 1,
    era: AcademicEra.Undergrad,
    explanation: 'Wernicke’s area supports language comprehension.'
  },
  {
    id: 'q_qcaa_13',
    text: 'A major ethical issue in early brain research methods was that they were often:',
    options: ['Too cheap', 'Risky and invasive for participants/patients', 'Completely non-invasive', 'Unable to produce any data'],
    correctIndex: 1,
    era: AcademicEra.WikiSkimmer,
    explanation: 'Historical methods often involved serious risk and invasive procedures.'
  },
  {
    id: 'q_qcaa_14',
    text: 'Knowledge of localisation of function helps psychologists because it can:',
    options: ['Predict likely effects of localised damage', 'Eliminate all individual differences', 'Replace behavioral testing entirely', 'Guarantee full recovery'],
    correctIndex: 0,
    era: AcademicEra.Ascended,
    explanation: 'Localisation helps predict cognitive/behavioral deficits from focal damage.'
  },
  {
    id: 'q_qcaa_15',
    text: 'Adolescence involves major brain changes including:',
    options: ['Reduced synaptic pruning', 'No forebrain development', 'Continued myelination and synaptic pruning', 'Complete halt in plasticity'],
    correctIndex: 2,
    era: AcademicEra.Undergrad,
    explanation: 'Adolescent development includes substantial pruning and ongoing myelination.'
  },
  {
    id: 'q_qcaa_16',
    text: 'Neural plasticity refers to the brain’s ability to:',
    options: ['Stop changing after childhood', 'Reorganise and adapt with experience or injury', 'Only grow in size', 'Encode only emotional memories'],
    correctIndex: 1,
    era: AcademicEra.WikiSkimmer,
    explanation: 'Plasticity is the capacity to change structure/function across development and experience.'
  },
  {
    id: 'q_qcaa_17',
    text: 'A “sensitive period” is best defined as:',
    options: ['A time when learning is impossible', 'A developmental window when certain experiences are especially influential', 'Any period after age 25', 'A period where only motor learning occurs'],
    correctIndex: 1,
    era: AcademicEra.Undergrad,
    explanation: 'Sensitive periods are windows of heightened responsiveness to specific input.'
  },
  {
    id: 'q_qcaa_18',
    text: 'Attachment is important in development because secure attachment is generally linked with:',
    options: ['Worse emotion regulation', 'Stronger social-emotional outcomes', 'Guaranteed high IQ only', 'No impact on stress response'],
    correctIndex: 1,
    era: AcademicEra.Undergrad,
    explanation: 'Secure attachment is associated with healthier social-emotional development.'
  },
  {
    id: 'q_qcaa_19',
    text: 'Early abuse or deprivation can negatively affect cognition by:',
    options: ['Improving executive function reliability', 'Disrupting stress systems and developmental pathways', 'Removing need for social interaction', 'Increasing cortical thickness uniformly'],
    correctIndex: 1,
    era: AcademicEra.Ascended,
    explanation: 'Early adverse environments can disrupt stress regulation and neural development.'
  },
  {
    id: 'q_qcaa_20',
    text: 'PET differs from MRI because PET primarily measures:',
    options: ['Magnetic properties of hydrogen only', 'Metabolic/functional activity via radiotracers', 'Direct electrical spikes at synapses', 'Structural white-matter tracts only'],
    correctIndex: 1,
    era: AcademicEra.Ascended,
    explanation: 'PET uses radiotracers to infer metabolic and functional processes.'
  }
];

export const MINIGAMES: MinigameDefinition[] = [
  {
    id: 'scam_o_matic',
    name: 'Scam-O-Matic',
    description: 'Pick cash or FLOPS, place a bet, and spin the scam reel. You might multiply your stack. You might fund someone else\'s yacht.',
    cost: 6800,
    dopamineReward: 0,
    cooldownMs: 180000,
    type: 'scam_o_matic'
  },
  {
    id: 'feed_sundgren',
    name: 'Feed Sundgren',
    description: 'Move left and right to catch falling snacks before morale drops to zero.',
    cost: 3900,
    dopamineReward: 11,
    cooldownMs: 140000,
    type: 'feed_sundgren'
  },
  {
    id: 'flappy_freud',
    name: 'Flappy Freud',
    description: 'Guide Freud through psychoanalytic defenses. Id below, superego above, therapy bill everywhere.',
    cost: 3600,
    dopamineReward: 9,
    cooldownMs: 140000,
    type: 'flappy_freud'
  },
  {
    id: 'brainbuilder',
    name: 'BrainBuilder',
    description: 'Stack squishy cortex blocks inside a live cranial x-ray before cognition collapses.',
    cost: 4200,
    dopamineReward: 10,
    cooldownMs: 150000,
    type: 'brainbuilder'
  },
  {
    id: 'neurosnake',
    name: 'NeuroSnake',
    description: 'Guide a glowing neuron and absorb electrical impulses before your cortex folds in on itself.',
    cost: 2800,
    dopamineReward: 6,
    cooldownMs: 120000,
    type: 'neurosnake'
  },
  {
    id: 'focus_tuner',
    name: 'Focus Tuner',
    description: 'Stop the signal inside the target window to earn dopamine.',
    cost: 750,
    dopamineReward: 6,
    cooldownMs: 90000,
    type: 'focus_tuner'
  },
  {
    id: 'signal_scan',
    name: 'Signal Scan',
    description: 'Find the target signal within limited attempts.',
    cost: 1800,
    dopamineReward: 10,
    cooldownMs: 120000,
    type: 'signal_scan'
  },
  {
    id: 'research_sim',
    name: 'Research Simulation',
    description: 'Plan a mini study and defend your design choices.',
    cost: 5200,
    dopamineReward: 24,
    cooldownMs: 150000,
    type: 'focus_tuner'
  }
];

export const NEUROLINK = {
  threshold: 90000,
  cost: 50000,
  passiveMultiplier: 1.7
};

export const INITIAL_CYBER_STOCKS: Stock[] = [
  {
    id: 'meta_google',
    ticker: 'MGL',
    name: 'Meta-Google OmniFeed',
    description: 'One company now owns search, social, and your grandparents\' opinions.',
    riskDescription: 'Reliable ad cashflow until regulators remember laws still exist.',
    detailOnClick: 'Synergy narrative is strong. Antitrust panic candles are stronger.',
    currentPrice: 2200,
    minPrice: 480,
    maxPrice: 14000,
    owned: 0,
    history: Array(20).fill(2200),
    volatility: 0.13,
    trend: 0.024,
    crashChance: 0.018,
    moonChance: 0.05,
    recoveryChance: 0.09,
    liquidity: 0.76,
    transactionFee: 0.011,
    riskLevel: 'Medium'
  },
  {
    id: 'elon_x',
    ticker: 'XLON',
    name: 'Elon_X Governance Bond',
    description: 'Backed by memes, rockets, and emergency polls.',
    riskDescription: 'Price moves violently whenever one person posts after midnight.',
    detailOnClick: 'This instrument confuses debt, equity, and social media velocity.',
    currentPrice: 5600,
    minPrice: 350,
    maxPrice: 42000,
    owned: 0,
    history: Array(20).fill(5600),
    volatility: 0.24,
    trend: 0.015,
    crashChance: 0.04,
    moonChance: 0.08,
    recoveryChance: 0.13,
    liquidity: 0.54,
    transactionFee: 0.016,
    riskLevel: 'High'
  },
  {
    id: 'cloud_prison_logistics',
    ticker: 'CPLX',
    name: 'Amazon-State Logistics Grid',
    description: 'Prime shipping now includes compulsory behavioral optimization.',
    riskDescription: 'High margins, high revolt risk, uncomfortably durable moat.',
    detailOnClick: 'Analysts call it defensive. Citizens call it inevitable.',
    currentPrice: 8900,
    minPrice: 900,
    maxPrice: 64000,
    owned: 0,
    history: Array(20).fill(8900),
    volatility: 0.19,
    trend: 0.028,
    crashChance: 0.027,
    moonChance: 0.062,
    recoveryChance: 0.1,
    liquidity: 0.61,
    transactionFee: 0.015,
    riskLevel: 'High'
  },
  {
    id: 'climate_derivative',
    ticker: 'BSKY',
    name: 'BlackSky Climate Swaps',
    description: 'Financial products on regional habitability futures.',
    riskDescription: 'Wins big in disasters. Correlation with ethics is approximately zero.',
    detailOnClick: 'Insurance math meets apocalypse cosplay.',
    currentPrice: 12200,
    minPrice: 1200,
    maxPrice: 105000,
    owned: 0,
    history: Array(20).fill(12200),
    volatility: 0.3,
    trend: 0.035,
    crashChance: 0.052,
    moonChance: 0.094,
    recoveryChance: 0.17,
    liquidity: 0.42,
    transactionFee: 0.021,
    riskLevel: 'Extreme'
  },
  {
    id: 'watercoin_cartel',
    ticker: 'H2OC',
    name: 'Watercoin Cartel',
    description: 'Tokenized freshwater rights traded with religious fervor.',
    riskDescription: 'Fundamentals are grimly bullish. Policy risk can still detonate pricing.',
    detailOnClick: 'When drought headlines trend, this thing goes vertical.',
    currentPrice: 7400,
    minPrice: 300,
    maxPrice: 120000,
    owned: 0,
    history: Array(20).fill(7400),
    volatility: 0.34,
    trend: 0.04,
    crashChance: 0.062,
    moonChance: 0.11,
    recoveryChance: 0.21,
    liquidity: 0.38,
    transactionFee: 0.024,
    riskLevel: 'Extreme'
  }
];

export const INITIAL_HARDWARE: Hardware[] = [
  {
    id: 'silicon_cortex',
    name: 'Neurochip',
    type: 'processor',
    baseCost: 250,
    effect: 24,
    heatGen: 0.45,
    powerDraw: 2.1,
    count: 0,
    description: 'First in-skull compute module. Cheap, fast, and morally ambiguous.'
  },
  {
    id: 'quantum_stack',
    name: 'Metro Data Center',
    type: 'processor',
    baseCost: 28000,
    effect: 220,
    heatGen: 3.2,
    powerDraw: 7.2,
    count: 0,
    description: 'Urban server block optimized for ad-tech, surveillance, and plausible deniability.'
  },
  {
    id: 'adversarial_farm',
    name: 'Continental Data Center',
    type: 'processor',
    baseCost: 420000,
    effect: 2800,
    heatGen: 24,
    powerDraw: 58,
    count: 0,
    description: 'Planet-scale compute slab. Massive FLOPS, massive draw, massive lawsuits.'
  },
  {
    id: 'cranial_vents',
    name: 'Cranial Vents',
    type: 'cooling',
    baseCost: 3200,
    effect: 1.35,
    heatGen: 0,
    powerDraw: 0.55,
    count: 0,
    description: 'Basic airflow for premium overclocking regret.'
  },
  {
    id: 'hypothalamic_cryoloop',
    name: 'Hypothalamic Cryoloop',
    type: 'cooling',
    baseCost: 9800,
    effect: 2.9,
    heatGen: 0,
    powerDraw: 1.35,
    count: 0,
    description: 'Closed-loop cryogenic coolant channels for panicked overclock events.'
  },
  {
    id: 'skull_battery_pack',
    name: 'Skull Battery Pack',
    type: 'power',
    baseCost: 6200,
    effect: 8,
    heatGen: 0.45,
    powerDraw: -8,
    count: 0,
    description: 'Compact in-cranium battery stack. Enough power to keep the wetware replacement online.'
  },
  {
    id: 'ocean_sink',
    name: 'Ocean Heat Sink',
    type: 'cooling',
    baseCost: 28000,
    effect: 5.6,
    heatGen: 0,
    powerDraw: 1.8,
    count: 0,
    description: 'Boil sections of the ocean for stable frame rates.'
  },
  {
    id: 'cryo_cathedral',
    name: 'Cryo Cathedral',
    type: 'cooling',
    baseCost: 180000,
    effect: 23,
    heatGen: 0.1,
    powerDraw: 6.8,
    count: 0,
    description: 'Subzero coolant loops powered by debt and denial.'
  },
  {
    id: 'deepwater_chiller_grid',
    name: 'Deepwater Chiller Grid',
    type: 'cooling',
    baseCost: 420000,
    effect: 58,
    heatGen: 0.18,
    powerDraw: 12,
    count: 0,
    description: 'Datacenter-scale water chillers. Expensive, thirsty, and very effective.'
  },
  {
    id: 'fusion_loan_plant',
    name: 'Nuclear Fission Plant',
    type: 'power',
    baseCost: 26000,
    effect: 16,
    heatGen: 1.4,
    powerDraw: -16,
    count: 0,
    description: 'Reliable base-load power with optional glowing river feature.'
  },
  {
    id: 'orbital_solar_swarm',
    name: 'Coal Hyperplant',
    type: 'power',
    baseCost: 85000,
    effect: 40,
    heatGen: 4.8,
    powerDraw: -40,
    count: 0,
    description: 'Turns ancient forests into immediate shareholder confidence.'
  },
  {
    id: 'waste_burning_plant',
    name: 'Waste-Burning Plant',
    type: 'power',
    baseCost: 145000,
    effect: 72,
    heatGen: 8.2,
    powerDraw: -72,
    count: 0,
    description: 'Incinerates "recyclables" for power. PR team calls it circular.'
  }
];

export const INITIAL_NETWORK_DEVICES: NetworkDevice[] = [
  {
    id: 'toaster_darkpool',
    name: 'Phishing Botnet',
    baseCost: 14000,
    effect: 58,
    powerDraw: 0.9,
    heatGen: 0.12,
    income: 320,
    count: 0,
    description: 'Credential harvesting at planetary scale. Mostly from suspicious links.'
  },
  {
    id: 'sentiment_tax_api',
    name: 'Blackmail Exchange API',
    baseCost: 72000,
    effect: 260,
    powerDraw: 2.6,
    heatGen: 0.45,
    income: 1700,
    count: 0,
    description: 'Monetizes private data leaks with a frictionless subscription model.'
  },
  {
    id: 'compliance_mirror',
    name: 'Crypto-Theft Mixer Grid',
    baseCost: 260000,
    effect: 960,
    powerDraw: 6.2,
    heatGen: 1.3,
    income: 5600,
    count: 0,
    description: 'Moves stolen wallets through enough chains to become "innovation."'
  },
  {
    id: 'orbital_cluster',
    name: 'Sovereign Heist Cloud',
    baseCost: 980000,
    effect: 3200,
    powerDraw: 18,
    heatGen: 3.9,
    income: 18000,
    count: 0,
    description: 'Off-world laundering cloud that bills itself as "decentralized trust."'
  }
];

export const MATTER_OPERATIONS: MatterOperationDefinition[] = [
  {
    id: 'minecraft_irl_program',
    name: 'Minecraft IRL Program',
    tagline: '"The children yearn for the mines."',
    description: 'A deeply cursed extraction initiative where management insists the uniforms are "educational." High matter yield, high moral bankruptcy.',
    baseCost: 1800,
    costGrowth: 1.26,
    matterPerSec: 0.95,
    heatPerSec: 0.08,
    energyDraw: 0.25,
    cashPerSec: -6
  },
  {
    id: 'landfill_strip_mining',
    name: 'Landfill Strip-Mining',
    tagline: 'Yesterday\'s gadgets, tomorrow\'s civilization.',
    description: 'Industrial excavation of e-waste strata. Reliable matter at the cost of heat and mild legal complications.',
    baseCost: 4200,
    costGrowth: 1.24,
    matterPerSec: 2.2,
    heatPerSec: 0.22,
    energyDraw: 0.6,
    cashPerSec: -10
  },
  {
    id: 'orbital_debris_harvesters',
    name: 'Orbital Debris Harvesters',
    tagline: 'Turning space junk into premium feedstock.',
    description: 'Autonomous tugs melt obsolete satellites into clean fabrication matter. Capital intensive, thermally efficient.',
    baseCost: 24000,
    costGrowth: 1.22,
    matterPerSec: 7.5,
    heatPerSec: 0.16,
    energyDraw: 1.4,
    cashPerSec: -18
  },
  {
    id: 'black_market_procurement',
    name: 'Black Market Procurement',
    tagline: 'No invoices. No questions. No refunds.',
    description: 'Converts cash into off-ledger matter deliveries. Expensive, volatile, and mysteriously punctual.',
    baseCost: 12000,
    costGrowth: 1.25,
    matterPerSec: 3.6,
    heatPerSec: 0.06,
    energyDraw: 0.35,
    cashPerSec: -140
  }
];
