import { AcademicEra, Question } from './types';
import { QCAA_EXAM_IMPORT_QUESTIONS } from './questionBankExamImport';

const q = (
  id: string,
  unit: string,
  topic: string,
  objectiveCode: string,
  text: string,
  options: string[],
  correctIndex: number,
  era: AcademicEra,
  explanation: string
): Question => ({
  id,
  unit,
  topic,
  objectiveCode,
  text,
  options,
  correctIndex,
  era,
  explanation
});

export const SYLLABUS_QUESTIONS: Question[] = [
  q('u1_t1_q1', 'Unit 1', 'The Role of the Brain', 'LO-1.01', 'Which statement best matches a materialist view of the mind-body problem?', ['Mind and body are separate substances', 'Mental states arise from brain processes', 'Consciousness exists independently of the body', 'Mind can never be scientifically investigated'], 1, AcademicEra.SmoothBrain, 'Materialism explains mental activity as a product of physical brain function.'),
  q('u1_t1_q2', 'Unit 1', 'The Role of the Brain', 'LO-1.01', 'René Descartes is most associated with which perspective?', ['Dualism', 'Behaviorism', 'Functionalism', 'Biological reductionism'], 0, AcademicEra.SmoothBrain, 'Descartes argued for mind-body dualism.'),
  q('u1_t1_q3', 'Unit 1', 'The Role of the Brain', 'LO-1.02', 'Why is phrenology considered pseudoscientific?', ['It used no hypotheses', 'It assumed skull shape reliably indicates psychological traits', 'It used experimental controls', 'It focused only on reflexes'], 1, AcademicEra.WikiSkimmer, 'Phrenology used invalid assumptions linking skull bumps to personality and ability.'),
  q('u1_t1_q4', 'Unit 1', 'The Role of the Brain', 'LO-1.02', 'Penfield advanced brain science mainly through:', ['Twin studies', 'Naturalistic observation', 'Direct cortical stimulation in neurosurgery', 'Longitudinal surveys'], 2, AcademicEra.WikiSkimmer, 'Penfield mapped functions using stimulation during surgery.'),

  q('u1_t1_q5', 'Unit 1', 'The Role of the Brain', 'LO-1.03', 'Which method has high temporal resolution for brain activity?', ['MRI', 'PET', 'EEG', 'CT'], 2, AcademicEra.WikiSkimmer, 'EEG captures rapid electrical changes over milliseconds.'),
  q('u1_t1_q6', 'Unit 1', 'The Role of the Brain', 'LO-1.03', 'Compared with EEG, fMRI is generally stronger in:', ['Temporal resolution', 'Spatial resolution', 'Portability', 'Cost effectiveness'], 1, AcademicEra.WikiSkimmer, 'fMRI localises activity more precisely in space.'),
  q('u1_t1_q7', 'Unit 1', 'The Role of the Brain', 'LO-1.04', 'The central nervous system includes:', ['Brain and spinal cord', 'Somatic and autonomic systems', 'Cranial nerves only', 'Endocrine glands'], 0, AcademicEra.SmoothBrain, 'CNS is composed of the brain and spinal cord.'),
  q('u1_t1_q8', 'Unit 1', 'The Role of the Brain', 'LO-1.04', 'The autonomic nervous system primarily regulates:', ['Voluntary skeletal movement', 'Automatic internal processes', 'Conscious memory recall', 'Speech perception'], 1, AcademicEra.SmoothBrain, 'Autonomic pathways regulate involuntary functions like heart rate and digestion.'),

  q('u1_t1_q9', 'Unit 1', 'The Role of the Brain', 'LO-1.05', 'Which neuron structure receives most incoming signals?', ['Axon terminal', 'Myelin sheath', 'Dendrites', 'Node of Ranvier'], 2, AcademicEra.SmoothBrain, 'Dendrites are specialised for input reception.'),
  q('u1_t1_q10', 'Unit 1', 'The Role of the Brain', 'LO-1.06', 'Motor neurons carry signals primarily:', ['From receptors to CNS', 'Between sensory receptors', 'From CNS to effectors', 'Across the corpus callosum'], 2, AcademicEra.SmoothBrain, 'Motor neurons transmit commands to muscles and glands.'),
  q('u1_t1_q11', 'Unit 1', 'The Role of the Brain', 'LO-1.07', 'The forebrain includes structures such as the:', ['Medulla only', 'Cerebral cortex', 'Spinal roots', 'Cochlea'], 1, AcademicEra.WikiSkimmer, 'The forebrain includes the cortex and higher-order structures.'),
  q('u1_t1_q12', 'Unit 1', 'The Role of the Brain', 'LO-1.08', 'Damage to Wernicke’s area most often impairs:', ['Language comprehension', 'Balance and posture', 'Primary vision', 'Fine motor precision'], 0, AcademicEra.WikiSkimmer, 'Wernicke’s area is strongly linked with language comprehension.'),

  q('u1_t1_q13', 'Unit 1', 'The Role of the Brain', 'SHE-1.01', 'A major ethical concern in early invasive brain research was:', ['Lack of statistics', 'Potential participant harm from risky procedures', 'Too much ecological validity', 'Excessive random allocation'], 1, AcademicEra.WikiSkimmer, 'Invasive historical methods often involved substantial patient risk.'),
  q('u1_t1_q14', 'Unit 1', 'The Role of the Brain', 'SHE-1.03', 'Understanding localisation helps psychologists to:', ['Guarantee complete recovery', 'Predict effects of localised damage', 'Eliminate cognitive testing', 'Avoid all individual differences'], 1, AcademicEra.WikiSkimmer, 'Localisation supports prediction of likely deficits after focal injury.'),
  q('u1_t1_q15', 'Unit 1', 'The Role of the Brain', 'LO-1.9', 'During adolescence, which process is strongly emphasised?', ['No neural change', 'Continued myelination and synaptic pruning', 'Only increases in neuron number', 'Loss of prefrontal function'], 1, AcademicEra.WikiSkimmer, 'Adolescent brain development includes pruning and ongoing myelination.'),
  q('u1_t1_q16', 'Unit 1', 'The Role of the Brain', 'LO-1.10', 'Neural plasticity refers to the brain’s ability to:', ['Stay fixed after childhood', 'Adapt and reorganise with experience', 'Store only emotional memories', 'Ignore environmental input'], 1, AcademicEra.WikiSkimmer, 'Plasticity is the capacity to change structure/function with experience or injury.'),

  q('u1_t2_q1', 'Unit 1', 'Cognitive Development', 'LO-1.11', 'Attachment is most closely linked with:', ['Random motor development', 'Social-emotional development patterns', 'Eye colour inheritance', 'Hearing threshold only'], 1, AcademicEra.WikiSkimmer, 'Attachment quality is associated with later emotional and social functioning.'),
  q('u1_t2_q2', 'Unit 1', 'Cognitive Development', 'LO-1.12', 'Early abuse/deprivation can negatively affect cognition by:', ['Increasing executive control reliably', 'Disrupting stress and developmental pathways', 'Improving sustained attention in all contexts', 'Removing need for social learning'], 1, AcademicEra.WikiSkimmer, 'Adverse early environments can alter neural development and later cognition.'),
  q('u1_t2_q3', 'Unit 1', 'Cognitive Development', 'LO-1.13', 'A key feature of Piaget’s theory is emphasis on:', ['Social scaffolding only', 'Stage-based cognitive restructuring', 'Operant conditioning schedules', 'Trait inheritance from twins'], 1, AcademicEra.WikiSkimmer, 'Piaget described qualitative stage changes in cognitive development.'),
  q('u1_t2_q4', 'Unit 1', 'Cognitive Development', 'LO-1.13', 'Vygotsky’s sociocultural perspective emphasises:', ['Independent discovery without others', 'Social interaction and cultural tools', 'Purely biological maturation', 'Randomized clinical interventions'], 1, AcademicEra.WikiSkimmer, 'Vygotsky highlighted social mediation and cultural context in learning.'),

  q('u1_t3_q1', 'Unit 1', 'Consciousness, Attention and Sleep', 'LO-1.14', 'The continuum of arousal ranges from:', ['REM to NREM only', 'Sleep through to hyperarousal', 'Perception to memory', 'Classical to operant conditioning'], 1, AcademicEra.WikiSkimmer, 'Arousal is viewed as a continuum from very low to very high activation states.'),
  q('u1_t3_q2', 'Unit 1', 'Consciousness, Attention and Sleep', 'LO-1.15', 'Divided attention involves:', ['Focusing on one target only', 'Processing multiple tasks/stimuli at once', 'Switching off awareness entirely', 'Automatic sensory adaptation only'], 1, AcademicEra.WikiSkimmer, 'Divided attention splits resources across multiple targets/tasks.'),
  q('u1_t3_q3', 'Unit 1', 'Consciousness, Attention and Sleep', 'LO-1.16', 'Melatonin release is linked to interaction between:', ['Thalamus and cerebellum', 'Hypothalamus and pineal gland', 'Amygdala and hippocampus', 'Broca’s and Wernicke’s areas'], 1, AcademicEra.WikiSkimmer, 'Hypothalamic control of circadian rhythms influences pineal melatonin secretion.'),
  q('u1_t3_q4', 'Unit 1', 'Consciousness, Attention and Sleep', 'LO-1.17', 'Which trio is commonly used to measure sleep/consciousness states?', ['MRI, PET, fMRI', 'EEG, EMG, EOG', 'CT, ECG, DNA', 'SCL-90, DSM, ICD'], 1, AcademicEra.WikiSkimmer, 'EEG, EMG and EOG are core sleep-lab measures.'),

  q('u1_t3_q5', 'Unit 1', 'Consciousness, Attention and Sleep', 'LO-1.18', 'REM sleep is typically associated with:', ['No brain activity', 'Rapid eye movement and vivid dreaming', 'Maximum muscle tone', 'Complete sensory shutdown'], 1, AcademicEra.WikiSkimmer, 'REM includes rapid eye movements and commonly vivid dream reports.'),
  q('u1_t3_q6', 'Unit 1', 'Consciousness, Attention and Sleep', 'LO-1.19', 'The restoration theory of sleep mainly argues that sleep:', ['Exists only for predator avoidance', 'Repairs and restores physiological systems', 'Is culturally irrelevant', 'Occurs without brain regulation'], 1, AcademicEra.WikiSkimmer, 'Restoration theory emphasises repair, recovery and homeostasis.'),
  q('u1_t3_q7', 'Unit 1', 'Consciousness, Attention and Sleep', 'LO-1.21', 'A likely consequence of sleep deprivation is:', ['Improved inhibitory control', 'Reduced attention and mood regulation', 'Perfect memory retrieval', 'Increased deep-sleep avoidance'], 1, AcademicEra.WikiSkimmer, 'Sleep loss impairs cognitive and emotional performance.'),
  q('u1_t3_q8', 'Unit 1', 'Consciousness, Attention and Sleep', 'LO-1.23', 'CPAP is most commonly used to treat:', ['Insomnia due to stress only', 'Obstructive sleep apnoea', 'Narcolepsy cataplexy only', 'Night terrors in all ages'], 1, AcademicEra.WikiSkimmer, 'CPAP supports airway patency in obstructive sleep apnoea.'),

  q('u2_t1_q1', 'Unit 2', 'Intelligence', 'LO-2.01', 'The psychometric approach to intelligence is most associated with:', ['Qualitative interviews only', 'Standardised measurement and IQ scores', 'Purely neural imaging markers', 'Case study narratives alone'], 1, AcademicEra.WikiSkimmer, 'Psychometrics uses standardised tests and statistical scaling.'),
  q('u2_t1_q2', 'Unit 2', 'Intelligence', 'LO-2.04', 'A reliable intelligence test should produce:', ['Different scores every day', 'Consistent scores across repeated testing', 'Only culturally neutral vocabulary items', 'No standard instructions'], 1, AcademicEra.WikiSkimmer, 'Reliability concerns consistency and stability of measurement.'),
  q('u2_t1_q3', 'Unit 2', 'Intelligence', 'LO-2.05', 'Twin and adoption studies are mainly used to examine:', ['Sleep architecture', 'Nature-nurture contributions to intelligence', 'Visual illusions', 'Autonomic nervous pathways'], 1, AcademicEra.Undergrad, 'These designs estimate genetic and environmental influence.'),
  q('u2_t1_q4', 'Unit 2', 'Intelligence', 'SHE-2.03', 'Cultural bias in IQ testing means that:', ['Tests are always invalid', 'Test content may advantage some cultural groups', 'All IQ scores are identical', 'Reliability becomes impossible'], 1, AcademicEra.Undergrad, 'Cultural loading can distort fairness and interpretation.'),

  q('u2_t2_q1', 'Unit 2', 'Diagnosis', 'LO-2.06', 'Maladaptive behaviour is best described as behaviour that:', ['Always increases wellbeing', 'Interferes with functioning and adaptation', 'Is uncommon but harmless', 'Occurs only in adolescence'], 1, AcademicEra.Undergrad, 'Maladaptive behaviour impairs coping, functioning or wellbeing.'),
  q('u2_t2_q2', 'Unit 2', 'Diagnosis', 'LO-2.09', 'DSM-5-TR and ICD-11 are both used to:', ['Measure neurotransmitter release', 'Classify and diagnose psychological disorders', 'Train reflex arcs', 'Map cortical gyri directly'], 1, AcademicEra.Undergrad, 'Both manuals provide classification criteria for disorders.'),
  q('u2_t2_q3', 'Unit 2', 'Diagnosis', 'LO-2.10', 'Which category includes schizophrenia?', ['Anxiety disorders', 'Schizophrenia spectrum and other psychotic disorders', 'Personality traits only', 'Learning disorders only'], 1, AcademicEra.Undergrad, 'Schizophrenia falls within the schizophrenia spectrum category.'),
  q('u2_t2_q4', 'Unit 2', 'Diagnosis', 'LO-2.11', 'Diagnostic validity refers to whether a diagnosis:', ['Is popular with clinicians', 'Accurately identifies the intended disorder', 'Uses short questionnaires only', 'Always predicts treatment success'], 1, AcademicEra.Undergrad, 'Validity asks whether the diagnosis captures the target construct.'),

  q('u2_t3_q1', 'Unit 2', 'Psychological Disorders and Treatments', 'LO-2.12', 'The biopsychosocial model explains disorder by combining:', ['Only biological causes', 'Biological, psychological and social factors', 'Only trauma history', 'Only diagnostic labels'], 1, AcademicEra.Undergrad, 'It integrates multiple interacting levels of influence.'),
  q('u2_t3_q2', 'Unit 2', 'Psychological Disorders and Treatments', 'LO-2.14', 'A core feature of specific phobia is:', ['Persistent fear tied to a specific object/situation', 'General reduced motivation', 'Delusions with disorganised speech', 'Elevated mood and grandiosity'], 0, AcademicEra.Undergrad, 'Specific phobia involves marked fear toward a defined stimulus.'),
  q('u2_t3_q3', 'Unit 2', 'Psychological Disorders and Treatments', 'LO-2.16', 'Psychotherapy differs from pharmacotherapy because psychotherapy primarily uses:', ['Medication dosage protocols', 'Psychological techniques and therapeutic relationship', 'Electrical stimulation only', 'Surgical lesion methods'], 1, AcademicEra.Undergrad, 'Psychotherapy relies on psychological intervention rather than medication.'),
  q('u2_t3_q4', 'Unit 2', 'Psychological Disorders and Treatments', 'LO-2.17', 'The placebo effect is best described as improvement due to:', ['The active pharmacological ingredient only', 'Expectancy/context rather than active treatment component', 'Random chance in all cases', 'Measurement error only'], 1, AcademicEra.Undergrad, 'Placebo responses reflect expectancy and treatment context effects.'),

  q('u2_t4_q1', 'Unit 2', 'Emotion and Motivation', 'LO-2.19', 'Schachter and Singer’s two-factor theory proposes emotion depends on:', ['Physiological arousal plus cognitive label', 'Arousal without cognition', 'Cognition without arousal', 'Only genetic temperament'], 0, AcademicEra.Undergrad, 'Two-factor theory combines arousal and cognitive appraisal/interpretation.'),
  q('u2_t4_q2', 'Unit 2', 'Emotion and Motivation', 'LO-2.20', 'The amygdala is most strongly associated with:', ['Visual acuity', 'Processing emotional salience, especially threat', 'Speech articulation', 'Spinal reflex integration'], 1, AcademicEra.Undergrad, 'The amygdala plays a central role in emotional processing.'),
  q('u2_t4_q3', 'Unit 2', 'Emotion and Motivation', 'LO-2.24', 'Mindfulness is most accurately defined as:', ['Suppressing all thoughts', 'Present-focused attention with non-judgmental acceptance', 'Maximising external rewards only', 'Avoiding emotional awareness'], 1, AcademicEra.Undergrad, 'Mindfulness combines attentional focus with acceptance.'),
  q('u2_t4_q4', 'Unit 2', 'Emotion and Motivation', 'LO-2.26', 'In self-efficacy theory, stronger efficacy expectations generally:', ['Reduce effort persistence', 'Increase effort and persistence on tasks', 'Eliminate need for goals', 'Guarantee immediate success'], 1, AcademicEra.Undergrad, 'Belief in capability tends to support persistence and performance.'),

  q('u3_t1_q1', 'Unit 3', 'Brain Function', 'LO-3.02', 'A monosynaptic spinal reflex includes:', ['One synapse between sensory and motor neuron', 'Multiple interneurons only', 'No spinal involvement', 'Cortical planning before movement'], 0, AcademicEra.Undergrad, 'Monosynaptic reflexes involve a single synapse in the reflex arc.'),
  q('u3_t1_q2', 'Unit 3', 'Brain Function', 'LO-3.03', 'Distributed processing means that cognitive tasks:', ['Depend on one isolated neuron', 'Involve interacting networks across regions', 'Occur only in hindbrain', 'Are unrelated to localisation'], 1, AcademicEra.Undergrad, 'Many functions emerge from interacting neural networks.'),
  q('u3_t1_q3', 'Unit 3', 'Brain Function', 'LO-3.07', 'During synaptic transmission, neurotransmitters are released from the:', ['Postsynaptic dendrite', 'Axon terminal into synaptic cleft', 'Myelin sheath into blood', 'Cell nucleus into ventricle'], 1, AcademicEra.Undergrad, 'Neurotransmitters are released from presynaptic terminals.'),
  q('u3_t1_q4', 'Unit 3', 'Brain Function', 'LO-3.08', 'GABA is generally classified as:', ['Excitatory only', 'Inhibitory', 'Hormonal peptide only', 'A sensory receptor'], 1, AcademicEra.Undergrad, 'GABA is the major inhibitory neurotransmitter in the CNS.'),

  q('u3_t1_q5', 'Unit 3', 'Brain Function', 'LO-3.09', 'Serotonin is commonly linked with regulation of:', ['Mood and arousal', 'Blood clotting only', 'Spinal cord growth only', 'Visual acuity only'], 0, AcademicEra.Undergrad, 'Serotonin has broad roles including mood and arousal regulation.'),
  q('u3_t1_q6', 'Unit 3', 'Brain Function', 'LO-3.10', 'Parkinson’s disease is strongly associated with disruption to:', ['Dopamine pathways', 'Retinal photoreceptors', 'Broca’s area only', 'Pineal melatonin release'], 0, AcademicEra.Undergrad, 'Parkinson’s involves degeneration affecting dopaminergic systems.'),
  q('u3_t1_q7', 'Unit 3', 'Brain Function', 'SHE-3.02', 'Plasticity after brain injury refers to:', ['No change after trauma', 'Functional reorganisation that can support recovery', 'Automatic full recovery without rehab', 'Only peripheral nerve repair'], 1, AcademicEra.Undergrad, 'Plasticity can support partial recovery through neural reorganisation.'),
  q('u3_t1_q8', 'Unit 3', 'Brain Function', 'SHE-3.04', 'Interfering with neurotransmitter systems can have:', ['Only beneficial outcomes', 'Beneficial and harmful consequences', 'No behavioural effects', 'Effects limited to spinal reflexes'], 1, AcademicEra.Undergrad, 'Neurochemical interventions can produce mixed outcomes.'),

  q('u3_t2_q1', 'Unit 3', 'Sensation and Perception', 'LO-3.11', 'In vision, transduction occurs when:', ['Light is converted into neural signals in the retina', 'Sound is converted in the cochlea', 'Signals bypass the thalamus always', 'Perception is consciously labelled only'], 0, AcademicEra.Undergrad, 'Photoreceptors transduce light energy into neural activity.'),
  q('u3_t2_q2', 'Unit 3', 'Sensation and Perception', 'LO-3.11', 'In hearing, the cochlea primarily:', ['Controls eye movement', 'Converts sound waves into neural impulses', 'Produces melatonin', 'Stores long-term memory'], 1, AcademicEra.Undergrad, 'Hair cells in the cochlea transduce sound vibration.'),
  q('u3_t2_q3', 'Unit 3', 'Sensation and Perception', 'LO-3.12', 'Top-down processing is most influenced by:', ['Receptor activation only', 'Prior knowledge and expectations', 'Purely random neural firing', 'Hormonal release only'], 1, AcademicEra.Undergrad, 'Top-down perception is shaped by context, expectation and prior knowledge.'),
  q('u3_t2_q4', 'Unit 3', 'Sensation and Perception', 'LO-3.13', 'Research on culture and perception suggests that perception is:', ['Entirely identical across cultures', 'Influenced by cultural experience and context', 'Unrelated to learning history', 'Unaffected by language'], 1, AcademicEra.Undergrad, 'Perceptual interpretation can vary with cultural learning and context.'),

  q('u3_t3_q1', 'Unit 3', 'Memory', 'LO-3.14', 'The multi-store model includes which sequence?', ['Sensory -> short-term -> long-term', 'Long-term -> sensory -> short-term', 'Working -> procedural -> semantic', 'Iconic -> episodic -> reflexive'], 0, AcademicEra.Undergrad, 'The Atkinson-Shiffrin model proposes sensory, short-term and long-term stores.'),
  q('u3_t3_q2', 'Unit 3', 'Memory', 'LO-3.16', 'Procedural memory is usually classified as:', ['Explicit semantic memory', 'Implicit long-term memory', 'Short-term auditory memory', 'Iconic sensory memory'], 1, AcademicEra.Undergrad, 'Procedural memory is an implicit memory type for skills.'),
  q('u3_t3_q3', 'Unit 3', 'Memory', 'LO-3.17', 'The hippocampus is especially important for:', ['Primary visual transduction', 'Formation of many explicit memories', 'Spinal reflex speed', 'Vestibular equilibrium only'], 1, AcademicEra.Undergrad, 'Hippocampal function is central to encoding/consolidating explicit memory.'),
  q('u3_t3_q4', 'Unit 3', 'Memory', 'LO-3.20', 'Retroactive interference occurs when:', ['Old learning disrupts new learning', 'New learning disrupts old learning retrieval', 'No memories are encoded', 'Recognition is always improved'], 1, AcademicEra.Undergrad, 'Retroactive interference means newer material impairs recall of older material.'),

  q('u3_t3_q5', 'Unit 3', 'Memory', 'LO-3.21', 'Which strategy best reflects spacing?', ['One long cramming session', 'Distributed study sessions over time', 'Random guessing only', 'Studying only when anxious'], 1, AcademicEra.Undergrad, 'Spaced practice improves retention by revisiting material over intervals.'),
  q('u3_t3_q6', 'Unit 3', 'Memory', 'LO-3.21', 'The method of loci improves memory by:', ['Reducing attention requirements', 'Linking items to imagined spatial locations', 'Avoiding retrieval cues', 'Suppressing rehearsal'], 1, AcademicEra.Undergrad, 'Method of loci uses spatial imagery cues to enhance recall.'),
  q('u3_t3_q7', 'Unit 3', 'Memory', 'LO-3.19', 'Recognition differs from recall because recognition:', ['Requires no memory store', 'Involves identifying previously learned information', 'Always has lower accuracy', 'Is only implicit'], 1, AcademicEra.Undergrad, 'Recognition presents cues and asks if information was seen before.'),
  q('u3_t3_q8', 'Unit 3', 'Memory', 'SHE-3.10', 'Why are memory findings sometimes open to interpretation?', ['Memory has no biological basis', 'Different methods and assumptions can support multiple explanations', 'Data are never replicable', 'Researchers always agree'], 1, AcademicEra.Ascended, 'Complex constructs and varied methods can support competing interpretations.'),

  q('u3_t4_q1', 'Unit 3', 'Learning', 'LO-3.23', 'Classical conditioning primarily links:', ['Behaviour to consequences', 'Two stimuli so one predicts the other', 'Learning to observational modelling only', 'Cognition to genetics directly'], 1, AcademicEra.Undergrad, 'Classical conditioning forms stimulus-stimulus associations.'),
  q('u3_t4_q2', 'Unit 3', 'Learning', 'LO-3.25', 'In operant conditioning, reinforcement:', ['Always weakens behaviour', 'Increases likelihood of behaviour', 'Only works with punishment', 'Requires unconscious reflexes'], 1, AcademicEra.Undergrad, 'Reinforcement increases future probability of a behaviour.'),
  q('u3_t4_q3', 'Unit 3', 'Learning', 'LO-3.26', 'Social learning theory emphasises:', ['Learning only through trial and error', 'Observational learning and modelling', 'Reflexive conditioning only', 'No role for cognition'], 1, AcademicEra.Undergrad, 'Bandura highlighted modelling and cognitive factors in learning.'),
  q('u3_t4_q4', 'Unit 3', 'Learning', 'SHE-3.14', 'A key ethical issue in Watson and Rayner’s Little Albert study was:', ['Excessive debriefing time', 'Inducing fear with limited safeguards', 'Overuse of double-blind controls', 'Use of fMRI in infants'], 1, AcademicEra.Ascended, 'The study involved ethically problematic induction of fear in a child participant.'),

  q('u4_t1_q1', 'Unit 4', 'Social Psychology', 'LO-4.01', 'Primary socialisation is most associated with:', ['Media algorithms', 'Family and early caregivers', 'Government policy only', 'Peer-reviewed journals'], 1, AcademicEra.Ascended, 'Primary socialisation occurs mainly in early family/caregiver contexts.'),
  q('u4_t1_q2', 'Unit 4', 'Social Psychology', 'LO-4.03', 'Internalisation occurs when a person:', ['Publicly complies but privately disagrees', 'Adopts group beliefs as personally valid', 'Ignores all social norms', 'Acts only under threat'], 1, AcademicEra.Ascended, 'Internalisation reflects genuine acceptance of group norms/beliefs.'),
  q('u4_t1_q3', 'Unit 4', 'Social Psychology', 'LO-4.05', 'Conformity is best described as behaviour change due to:', ['Direct monetary reinforcement only', 'Real or imagined group pressure', 'Neurological degeneration', 'Classical conditioning alone'], 1, AcademicEra.Ascended, 'Conformity involves alignment with group expectations.'),
  q('u4_t1_q4', 'Unit 4', 'Social Psychology', 'LO-4.06', 'Milgram’s obedience research showed that:', ['Authority has no effect on behaviour', 'Perceived legitimate authority can strongly increase obedience', 'Conformity always decreases in labs', 'Status never changes behaviour'], 1, AcademicEra.Ascended, 'Milgram demonstrated substantial obedience under authority pressure.'),

  q('u4_t2_q1', 'Unit 4', 'Interpersonal Processes', 'LO-4.07', 'Latané and Darley’s bystander findings are commonly explained by:', ['Sensory adaptation', 'Diffusion of responsibility', 'Operant extinction', 'Classical generalisation'], 1, AcademicEra.Ascended, 'Presence of others can diffuse perceived personal responsibility to act.'),
  q('u4_t2_q2', 'Unit 4', 'Interpersonal Processes', 'LO-4.08', 'The reciprocity principle suggests people are more likely to help when:', ['No prior interaction exists', 'They have received help or benefit from others', 'Costs are always high', 'Social norms prohibit helping'], 1, AcademicEra.Ascended, 'Reciprocity norms motivate returning support/help.'),
  q('u4_t2_q3', 'Unit 4', 'Interpersonal Processes', 'LO-4.11', 'In the General Aggression Model, aggressive behaviour is influenced by:', ['Only biological predisposition', 'Person and situational inputs over episodes', 'Only media exposure', 'Only trait empathy'], 1, AcademicEra.Ascended, 'GAM integrates personal and situational factors in aggression pathways.'),
  q('u4_t2_q4', 'Unit 4', 'Interpersonal Processes', 'LO-4.14', 'Which factor is a common social-cognitive origin of attraction?', ['Proximity', 'Synaptic pruning', 'Pineal secretion', 'Auditory masking'], 0, AcademicEra.Ascended, 'Proximity increases opportunities for interaction and relationship formation.'),

  q('u4_t3_q1', 'Unit 4', 'Attitudes', 'LO-4.16', 'The tri-component model includes:', ['Cognition, affect, behaviour', 'Memory, arousal, perception', 'Trait, state, role', 'Nature, nurture, chance'], 0, AcademicEra.Ascended, 'Attitudes are often conceptualised as cognitive, affective and behavioural components.'),
  q('u4_t3_q2', 'Unit 4', 'Attitudes', 'LO-4.18', 'Cognitive dissonance is typically experienced as:', ['Comfort from consistency', 'Discomfort from inconsistency between beliefs and behaviour', 'A memory deficit only', 'A sensory threshold shift'], 1, AcademicEra.Ascended, 'Dissonance motivates efforts to restore consistency.'),
  q('u4_t3_q3', 'Unit 4', 'Attitudes', 'LO-4.20', 'The fundamental attribution error is the tendency to:', ['Overestimate situational causes for others', 'Overestimate dispositional causes for others', 'Ignore dispositional causes in self', 'Treat all causes equally'], 1, AcademicEra.Ascended, 'People often over-attribute others’ behaviour to personal traits.'),
  q('u4_t3_q4', 'Unit 4', 'Attitudes', 'LO-4.24', 'Prejudice differs from discrimination because prejudice is:', ['Behaviour while discrimination is attitude', 'Attitude while discrimination is behaviour', 'Always explicit and behavioural', 'Equivalent in all contexts'], 1, AcademicEra.Ascended, 'Prejudice is an attitude; discrimination is behaviour toward groups.'),

  q('u4_t4_q1', 'Unit 4', 'Cross-Cultural Psychology', 'LO-4.27', 'In psychology, culture refers to shared:', ['Genes only', 'Behaviours, beliefs and values', 'Neural pathways only', 'Diagnostic categories only'], 1, AcademicEra.Ascended, 'Culture includes shared meanings, values, norms and practices.'),
  q('u4_t4_q2', 'Unit 4', 'Cross-Cultural Psychology', 'LO-4.28', 'Pluralism differs from multiculturalism when:', ['There is no cultural diversity', 'A dominant culture is absent', 'All groups assimilate fully', 'Only one language is permitted'], 1, AcademicEra.Ascended, 'Pluralism emphasises coexistence without a single dominant culture.'),
  q('u4_t4_q3', 'Unit 4', 'Cross-Cultural Psychology', 'LO-4.29', 'Acculturation stress commonly involves challenges related to:', ['Only sensory adaptation', 'Culture shock, identity and social integration', 'Purely genetic mismatch', 'Only memory capacity'], 1, AcademicEra.Ascended, 'Immigration and acculturation can create identity, social and adaptation stressors.'),
  q('u4_t4_q4', 'Unit 4', 'Cross-Cultural Psychology', 'LO-4.31', 'According to contact approaches, prejudice is reduced most effectively by contact that is:', ['Brief and competitive', 'Sustained, equal-status and cooperative', 'Anonymous and online only', 'Forced without shared goals'], 1, AcademicEra.Ascended, 'Intergroup contact is strongest with sustained equal-status cooperation and shared goals.'),
  ...QCAA_EXAM_IMPORT_QUESTIONS
];
