
export enum RegionName {
    Brainstem = 'brainstem',
    Cerebellum = 'cerebellum',
    Limbic = 'limbic',
    Temporal = 'temporal',
    Parietal = 'parietal',
    Frontal = 'frontal',
    Occipital = 'occipital'
}

export interface Region {
    id: RegionName;
    name: string;
    description: string;
    level: number;
    unlocked: boolean;
    unlockCost: number; // Neurons
    examPassesRequired: number; // Number of correct quiz answers needed to unlock
}

export interface Upgrade {
    id: string;
    region: RegionName;
    name: string;
    description: string;
    cost: number;
    currency: 'neurons' | 'dopamine' | 'serotonin';
    effectType:
      | 'click'
      | 'passive'
      | 'anxiety_cap'
      | 'anxiety_resist'
      | 'dopamine_gain'
      | 'serotonin_gain'
      | 'crit_chance'
      | 'crit_mult'
      | 'streak_boost'
      | 'visual_fx'
      | 'stock_unlock';
    value: number;
    unlockStockId?: string;
    purchased: boolean;
    reqRegionLevel: number;
    maxPurchases?: number;
    count?: number;
}

export type StockPersonality = 'momentum' | 'mean_reversion' | 'boom_bust' | 'chaos' | 'defensive';
export type StockRegime = 'calm' | 'hype' | 'panic' | 'dead';
export type StockSector = 'study' | 'health' | 'creator' | 'chaos' | 'infrastructure' | 'megacorp';
export type MarketScenario = 'bull_week' | 'panic_week' | 'fake_news_week';

export interface Stock {
    id: string;
    ticker: string;
    name: string;
    description: string;
    riskDescription?: string; // Why is this risky?
    detailOnClick?: string;
    currentPrice: number;
    minPrice: number;
    maxPrice: number;
    owned: number;
    history: number[]; // Last 20 price points for graph
    volatility: number; // How wildly it swings
    trend: number; // Bias towards up or down
    crashChance: number; // Chance of severe collapse on a stock update
    moonChance: number; // Chance of sudden upside spike on a stock update
    recoveryChance: number; // Chance to recover from near-zero state
    liquidity: number; // Higher = tighter spreads and easier exits
    transactionFee: number; // Base fee rate for buy/sell
    totalCostBasis?: number; // Cost basis for currently held units
    realizedPnl?: number; // Realized P/L from closed units
    riskLevel: 'Low' | 'Medium' | 'High' | 'Extreme';
    personality?: StockPersonality;
    regime?: StockRegime;
    regimeTicksLeft?: number; // Countdown to possible regime shift
    sector?: StockSector;
    volatilityCluster?: number; // Captures volatility clustering over time
    signalReliability?: number; // 0..1 confidence in predictive signals
    momentumSignal?: number; // -1..1
    sentimentSignal?: number; // -1..1
    fundamentalSignal?: number; // -1..1
    lastEventImpact?: number; // -1..1 event pressure currently applied
}

export interface Hardware {
    id: string;
    name: string;
    type: 'processor' | 'cooling' | 'power';
    baseCost: number;
    effect: number; // throughput for processor, heat reduction for cooling, supply for power
    heatGen: number; // heat generated by processor or power hardware
    powerDraw: number; // demand for processor/cooling, can be negative for power generators
    count: number;
    description: string;
}

export interface NetworkDevice {
    id: string;
    name: string;
    baseCost: number;
    effect: number; // passive throughput
    powerDraw: number; // electrical load
    heatGen: number; // thermal output
    income: number; // money siphoned per second
    count: number;
    description: string;
}

export interface MatterOperationDefinition {
    id: string;
    name: string;
    tagline: string;
    description: string;
    baseCost: number; // cash
    costGrowth: number;
    matterPerSec: number;
    heatPerSec: number;
    energyDraw: number;
    cashPerSec?: number; // positive = earns cash, negative = burns cash
}

export enum AcademicEra {
    SmoothBrain = 0,   // Proto
    WikiSkimmer = 1,   // Basic
    Undergrad = 2,     // Theory
    Ascended = 3       // Meta/Horror
}

export enum GamePhase {
    Biological = 'biological',
    NeuroLink = 'neurolink',
    Megacorp = 'megacorp',
    Quantum = 'quantum',
    Space = 'space',
    Rival = 'rival'
}

export interface Question {
    id: string;
    text: string;
    options: string[];
    correctIndex: number;
    era: AcademicEra;
    explanation: string;
    unit?: string;
    topic?: string;
    objectiveCode?: string;
}

export interface LogMessage {
    id: string;
    text: string;
    timestamp: number;
    type: 'info' | 'alert' | 'epiphany' | 'panic' | 'breakdown' | 'market';
}

export interface MiniGameState {
    id: string;
    owned: boolean;
    lastPlayed: number; // timestamp
}

export interface MinigameDefinition {
    id: string;
    name: string;
    description: string;
    cost: number;
    dopamineReward: number;
    cooldownMs: number;
    type: 'focus_tuner' | 'signal_scan' | 'neurosnake' | 'brainbuilder' | 'flappy_freud' | 'feed_sundgren' | 'scam_o_matic';
}

export interface GameState {
    // Currencies
    neurons: number;
    dopamine: number; // Spendable currency now
    serotonin: number; // Spendable currency now
    money: number; // Digital phase currency
    
    // Stats
    totalNeurons: number;
    clickPower: number;
    passiveGen: number;
    dopamineGainChance: number;
    serotoninPerCorrect: number;
    critChance: number;
    critMultiplier: number;
    streakBoost: number;
    clickStreak: number;
    lastManualClick: number;
    clickFxLevel: number;
    computeMultiplier: number;
    isCyborg: boolean;
    phase: GamePhase;
    
    // Mental Health
    anxiety: number; // 0-100
    anxietyCap: number; // Breakdown threshold
    anxietyResist: number; // Multiplier (lower is better)
    breakdownActive: boolean;
    breakdownTimer: number; // Seconds remaining
    
    // Progression
    regions: Record<RegionName, Region>;
    academicEra: AcademicEra;
    correctQuizAnswers: number; // Lifetime correct answers (for gating)
    
    // Market
    stocks: Stock[];
    lastStockUpdate: number;
    marketHeadline: string;
    marketHeadlineUntil: number;
    marketMood: number; // -1..1 aggregate mood
    marketScenario: MarketScenario;
    marketScenarioWeekKey: string;
    marketEventSector: StockSector | 'all' | null;
    marketEventBias: number;
    marketEventSeverity: number;
    cyborgResearchPoints: number; // Correct answers earned in NeuroLink stage, used to unlock advanced infrastructure
    psychBucks: number; // Milestone reward currency for cosmetics/jokes shop
    claimedMilestoneIqs: number[]; // IQ milestone thresholds already rewarded
    shopOwnedIds: string[]; // Purchased reward IDs
    activeCosmeticId: string | null; // Equipped cosmetic theme ID
    compute: number; // Megacorp compute credits
    matter: number; // Megacorp fabrication matter
    water: number; // Cooling water reserve
    waterCapacity: number; // Max water storage
    energy: number; // Megacorp power buffer
    heat: number; // Megacorp thermal load
    heatCapacity: number; // Current thermal capacity before throttling
    prLevel: number; // Megacorp public relations index (0-100)
    globalAnxiety: number; // Megacorp threat meter (0-100)
    nudges: number; // Earned from quiz in Megacorp, spent on PR + distractions
    corporateTaxDrain: number; // Passive capital drain baseline
    prUpgrades: string[]; // Purchased PR upgrade IDs
    activeDistractions: Record<string, number>; // Active distraction timers in ms
    behavioralNudges: number; // Earned from quiz answers in Megacorp
    realEstate: number; // Usable acres for infrastructure
    megacorpBaselineRealEstate: number; // Acreage snapshot at Megacorp start (used for anxiety ramp)
    earthSubjugatedPercent: number; // Progress to post-Earth phases
    antitrustCooldown: number; // Seconds remaining for hearing penalty
    senateBaffleProgress: number; // Correct answers used to end hearing
    operantCampaigns: number; // Purchased campaign stacks
    dissonanceCampaigns: number; // Purchased campaign stacks
    lobbyingLevel: number; // Softens global anxiety pressure
    earthMatterTotal: number;
    earthMatterRemaining: number;
    spaceProgressUnlocked: boolean;
    spaceSectorsScanned: number;
    spaceSectorsTotal: number;
    spaceGalaxiesDiscovered: number;
    spaceGalaxiesClaimed: number;
    spaceRelays: number;
    spaceHostileSignals: number;
    spaceSurveyMissions: number;
    spaceRaidCooldown: number;
    spaceMatterExtracted: number;
    bleatFeed: string[];
    bleatTickerMs: number;
    revoltPending: boolean;
    matterOps: Record<string, number>;

    // Minigames / progression
    minigames: Record<string, MiniGameState>;
    digitalBrainUnlocked: boolean;
    digitalNetworkUnlocked: boolean;
    digitalMiningUnlocked: boolean;
    neuroLinkStartedAt: number;
    hardware: Hardware[];
    network: NetworkDevice[];
    
    lastTick: number;
}

export const INITIAL_STATE: GameState = {
    neurons: 0,
    dopamine: 0,
    serotonin: 0,
    money: 0,
    totalNeurons: 0,
    clickPower: 1,
    passiveGen: 0,
    dopamineGainChance: 0.2,
    serotoninPerCorrect: 5,
    critChance: 0.1,
    critMultiplier: 3,
    streakBoost: 0.02,
    clickStreak: 0,
    lastManualClick: 0,
    clickFxLevel: 0,
    computeMultiplier: 1,
    isCyborg: false,
    phase: GamePhase.Biological,
    anxiety: 0,
    anxietyCap: 100,
    anxietyResist: 1,
    breakdownActive: false,
    breakdownTimer: 0,
    regions: {
        [RegionName.Brainstem]: { 
            id: RegionName.Brainstem, 
            name: 'Brainstem', 
            description: 'Core regulation systems and baseline arousal.', 
            level: 1, 
            unlocked: true, 
            unlockCost: 0, 
            examPassesRequired: 0 
        },
        [RegionName.Cerebellum]: { 
            id: RegionName.Cerebellum, 
            name: 'Cerebellum', 
            description: 'Procedural learning, movement precision, and skill rehearsal.', 
            level: 0, 
            unlocked: false, 
            unlockCost: 300, 
            examPassesRequired: 2 
        },
        [RegionName.Limbic]: { 
            id: RegionName.Limbic, 
            name: 'Limbic System', 
            description: 'Emotion, motivation, and reinforcement processes.', 
            level: 0, 
            unlocked: false, 
            unlockCost: 1200, 
            examPassesRequired: 3 
        },
        [RegionName.Temporal]: {
            id: RegionName.Temporal,
            name: 'Temporal Lobe',
            description: 'Memory encoding, retrieval, and language comprehension.',
            level: 0,
            unlocked: false,
            unlockCost: 3400, 
            examPassesRequired: 4
        },
        [RegionName.Parietal]: {
            id: RegionName.Parietal,
            name: 'Parietal Lobe',
            description: 'Spatial processing, attention, and somatosensory integration.',
            level: 0,
            unlocked: false,
            unlockCost: 8500, 
            examPassesRequired: 6
        },
        [RegionName.Occipital]: { 
            id: RegionName.Occipital, 
            name: 'Occipital Lobe', 
            description: 'Visual cognition and pattern recognition in data and stimuli.', 
            level: 0, 
            unlocked: false, 
            unlockCost: 19000, 
            examPassesRequired: 8 
        },
        [RegionName.Frontal]: { 
            id: RegionName.Frontal, 
            name: 'Frontal Cortex', 
            description: 'Executive control, decision making, and metacognition.', 
            level: 0, 
            unlocked: false, 
            unlockCost: 42000, 
            examPassesRequired: 10 
        }
    },
    academicEra: AcademicEra.SmoothBrain,
    correctQuizAnswers: 0,
    stocks: [], // Will be populated from constants
    lastStockUpdate: Date.now(),
    marketHeadline: '',
    marketHeadlineUntil: 0,
    marketMood: 0,
    marketScenario: 'bull_week',
    marketScenarioWeekKey: '',
    marketEventSector: null,
    marketEventBias: 0,
    marketEventSeverity: 0,
    cyborgResearchPoints: 0,
    psychBucks: 0,
    claimedMilestoneIqs: [],
    shopOwnedIds: [],
    activeCosmeticId: null,
    compute: 0,
    matter: 0,
    water: 0,
    waterCapacity: 160,
    energy: 0,
    heat: 0,
    heatCapacity: 60,
    prLevel: 100,
    globalAnxiety: 0,
    nudges: 0,
    corporateTaxDrain: 40,
    prUpgrades: [],
    activeDistractions: {},
    behavioralNudges: 0,
    realEstate: 0,
    megacorpBaselineRealEstate: 0,
    earthSubjugatedPercent: 0,
    antitrustCooldown: 0,
    senateBaffleProgress: 0,
    operantCampaigns: 0,
    dissonanceCampaigns: 0,
    lobbyingLevel: 0,
    earthMatterTotal: 0,
    earthMatterRemaining: 0,
    spaceProgressUnlocked: false,
    spaceSectorsScanned: 0,
    spaceSectorsTotal: 1400,
    spaceGalaxiesDiscovered: 0,
    spaceGalaxiesClaimed: 0,
    spaceRelays: 0,
    spaceHostileSignals: 0,
    spaceSurveyMissions: 0,
    spaceRaidCooldown: 0,
    spaceMatterExtracted: 0,
    bleatFeed: [],
    bleatTickerMs: 5000,
    revoltPending: false,
    matterOps: {},
    minigames: {},
    digitalBrainUnlocked: false,
    digitalNetworkUnlocked: false,
    digitalMiningUnlocked: false,
    neuroLinkStartedAt: 0,
    hardware: [],
    network: [],
    lastTick: Date.now(),
};
